apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: helloworld-go # The name of the app
  namespace: default # The namespace the app will use
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/koduki-docker-test-001-1083/sqljudge/app
            env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
